language: node_js
node_js:
  - "8"
  - "10"
cache:
  yarn: true
  directories:
    - "node_modules"
before_install: yarn global add greenkeeper-lockfile@1
install:
  - yarn install
  - yarn run install-self-peers
before_script: greenkeeper-lockfile-update
script:
  - yarn run flow
  - yarn run lint
after_script: greenkeeper-lockfile-upload
